### ISSUE TITLE
Playwright support 

### ISSUE THREAD

**Issue by skuam** [lavague-ai/LaVague#1]
Do you plan to support playwright?

**Comment by dhuynh95** [comment]
I might not have time to but it should not be complicated. If you look at the code, you just need to load the driver first, then you will have to edit the prompt template to adapt it for playwright

**Comment by afsarali-pg** [comment]
I would love to contribute for this feature . Plz let me know what would be starting point for me to see any example

**Comment by lyie28** [comment]
Hey @afsarali-pg,

That would be awesome!

We are just cleaning and re-organizing the codebase into a modular python package with a CLI to make it easier for people to build on- this should be done in the next few days.

I'll let you know when that is done and give you some more info then. But the task should mainly consist of adding a playwrite specific prompt instead of the default one (see default_prompt.py on the 'pypi' branch), and adding a Playwrite option for the CLI which will use the relevant Playwrite code instead of the Selenium driver/set-up code.

Please bear with us whilst we finish re-organizing the code!

**Comment by lyie28** [comment]
Hey @afsarali-pg,

For now, we have created a Python package for the AI Engine and have updated our notebook accordingly.

The AI Engine takes HTML source code, splitting it up into smaller chunks, indexing it with an embedding model and getting the most relevant HTML code:
`action_engine.get_query_engine(source-code)`

It then takes user instructions and inserts the into the default prompt and queries the LLM with that prompt:
`query_engine.query(user_instructions)`

For now, we have not added any CLI, meaning that if you are not using the Gradio notebook and are just use the Pypi package directly, you need to:
- Provide the HTML source code
- Do the necessary set-up code for whatever automation tool you are using Selenium, Playwright or whatever
- The response you get back from the query is the code generated by the LLM which you can then execute with `exec(response)` for example to perform the desired task

So, for now, you could already get started by:
1. Creating a Playwright specific prompt template
2. Adding an option to the 'get_query_engine' method so we can specify that the Playwright prompt template should be used and not the default one (currently there is prompt_template = PromptTemplate(DEFAULT_PROMPT))
3. Copying our latest notebook but modify to install your locally modified package, use your new playwright prompt and replace any Selenium specific code with any needed Playwright replacement !

Let me know if you have any questions! I am working on documentation as we speak so there should be more information coming soon!

**Comment by lyie28** [comment]
Hey @afsarali-pg,

As you may have noticed - the code base has grown quite a lot since we last spoke!  We also have [docs now](https://docs.lavague.ai/en/latest/)

Are you still wanting to work on the Playwright feature, as we are looking to assign this to someone? Are you on Discord? If so, could be continue the discussions there: #lyie7069

**Comment by shubhamofbce** [comment]
@lyie28 I am interested to pick this up. You can assign this to me.

**Comment by lyie28** [comment]
Okay, so we'll assign this one to @shubhamofbce ! 

@afsarali-pg, get in touch with us if/when you are available for contributing and we can see if there is another task on the backlog we can assign to you
