### ISSUE TITLE
Playwright generated code is not good enough

### ISSUE THREAD

**Issue by mbrunel** [lavague-ai/LaVague#133]
@shubhamofbce @dhuynh95 

It may come from the prompt template, it requires more investigations.

**Comment by shubhamofbce** [comment]
Lets get on a call today to discuss this. @mbrunel

**Comment by shubhamofbce** [comment]
I will look into this. @lyie28 can you please assign this to me.

**Comment by dhuynh95** [comment]
By the way, I have an Eval class being prepared: https://github.com/lavague-ai/LaVague/issues/120

The second metric is recall_LLM which might be useful to evaluate performance of prompts

**Comment by shubhamofbce** [comment]
These are some actual issues that i found in the first look:
1. If you do `find_element_by_` in selenium, it by default picks up the 1st element unless you do `find_elements_by_` but in playwright the `locator` function we are using returns all matching elements and if there are multiple matching instances. It is unable to click on it.
2. Our default example instruction says go to datasets page. playwright uses go to function to open a url so it just tries to open some random datasets url in a new tab instead of finding datasets section on the current page. This can be fixed by updating the instructions.
I am working on finding more such fundamental issues and fixing them one by one.
cc: @dhuynh95 @mbrunel
