### ISSUE TITLE
Add docker option to "getting started"

### ISSUE THREAD

**Issue by Dbz** [lavague-ai/LaVague#16]
**Is your feature request related to a problem? Please describe.**
Add a way for people to test and run this locally - not in a codelab. Docker is an easy path for folks.

**Describe the solution you'd like**
I'd like clear instructions on how to run this locally.

**Comment by lyie28** [comment]
Hey there,

Our next step is to provide the code as a Python package.

A docker would be a nice addition, but we won't have time to work on it for now so I've put it into our help-wanted section.

**Comment by smach** [comment]
Python package would be another excellent option to run locally, thanks! You may want to change the website docs here, though, because it says that a Docker image is "coming soon"? Doesn't sound like it's expected soon. [https://docs.lavague.ai/en/latest/docs/get-started/get-started-docker/](https://docs.lavague.ai/en/latest/docs/get-started/get-started-docker/)

**Comment by lyie28** [comment]
@smach Thanks for flagging. In the end, we have decided to go with a dev Container option - have updated the docs: https://docs.lavague.ai/en/latest/docs/get-started/setting-up-la-vague/

**Comment by lyie28** [comment]
We also created a docker image in the end too: https://docs.lavague.ai/en/latest/docs/get-started/setting-up-la-vague/
