### ISSUE TITLE
Documentation should not say to run setup.sh with sudo

### ISSUE THREAD

**Issue by gbreed** [lavague-ai/LaVague#164]
**Describe the bug**

Documentation in multiple places tells us to run ``sudo bash setup.sh``.  This doesn't work.  It will try to install the Python module as the root user.  The script includes ``sudo`` calls when required and is clearly not intended to be run as root.

**To Reproduce**
1. Go to <https://docs.lavague.ai/en/latest/>
2. Follow the installation instructions
3. The LaVague command won't run for me

This might be specifically broken on Ubuntu because it doesn't allow system installs through pip.  It looks like it should work generally if you activate your virtualenv before running the script.

**Expected behavior**

I think it should install the package into a virtualenv.  If I fix the ownership of the different things that were downloaded as root and run ``pip install -e LaVague`` that works.

As the last step is to change directory, it might be that this script is intended to be sourced rather than run.

One other thing: when it fails I don't expect it to tell me it was successful.  The setup script should have a ``set -e`` at the top

**Comment by dhuynh95** [comment]
Thanks for pointing that out.
@JoFrost could you have a look?

**Comment by lyie28** [comment]
Hi @gbreed,

Thanks for reporting this and your suggestions.

I have:
- Removed sudo from instructions for running the script in the docs
- Added a set -e and an error message into the setup script
- Changed from install from GH repo to install from pypi package (originally we installed from the repo because the project was changing very rapidly and the changes were not always reflected in the package)

What do you think? Can you confirm that this solves your issue?

**Comment by gbreed** [comment]
It solves the issue of installing the Python module.  If I run it I still get this:

{{{
Error: Invalid value for '--instructions' / '-i': Path 'examples/instructions/huggingface.yaml' does not exist.
}}}

I'm trying to use huggingface because I can get a free key for testing.  There are a number of things that aren't clear in the documentation but I don't know how helpful I can be about fixing them while I don't have it working
________________________________

**Comment by lyie28** [comment]
@gbreed - actually it just occured to me that since I change to a pip install in the script, we won't necessary have the GH repo with demo config + instructions files downloaded - sorry about that.

You can do the following instead if you don't want to clone the whole repo:
1. Install directly the HF demo instructions + config files (or download the whole GH repo):

wget https://raw.githubusercontent.com/lavague-ai/LaVague/main/examples/configurations/api/huggingface_inference.py
wget https://raw.githubusercontent.com/lavague-ai/LaVague/main/examples/instructions/huggingface.yaml

Note, if you install them this way the paths of your two files will be different since we install them to your current directory, so it will be: 
lavague -c huggingface_inference.py -i huggingface.yaml launch

2. Make sure to install the additional dependencies required for the HF API:
pip install lavague[cuda]
pip install lavague[huggingface]

3. Make sure you have a HF_TOKEN environment variable set with your HF API key

This HF specific guide might be helpful: https://docs.lavague.ai/en/latest/docs/integrations/api/hugging-face/

**Comment by gbreed** [comment]
Okay, yes, I'd missed those two pip installs.  I was following the integration guide, and I can see them in there, but for some reason I skipped over them.  It's now giving me this problem:

  File "/home/graham/.virtualenvs/LaVague/lib/python3.11/site-packages/transformers/utils/generic.py", line 465, in <module>
    import torch.utils._pytree as _torch_pytree
  File "/home/graham/.virtualenvs/LaVague/lib/python3.11/site-packages/torch/utils/__init__.py", line 4, in <module>
    from .throughput_benchmark import ThroughputBenchmark
  File "/home/graham/.virtualenvs/LaVague/lib/python3.11/site-packages/torch/utils/throughput_benchmark.py", line 2, in <module>
    import torch._C
ModuleNotFoundError: No module named 'torch._C'


I still have the git checkout, and it is useful when links don't work in the documentation.  I can see there's an issue raised about this.  I also have a couple of spelling mistakes I've fixed locally: "HUGGINFACE" in that integration guide and "Playright" in the page about Playwright.


         Graham
________________________________

**Comment by lyie28** [comment]
Thanks @gbreed. I've just pushed an update to fix dead links and the typos you mentioned 👍

I will build an automatic CI for the docs soon to avoid/reduce this kind of thing but just haven't had the time yet as there's been a lot going on. If you spot anything else, please do let me know and I'll fix them or do a PR and I'll merge it :)

As for your bug, seems to be an issue with the torch installation/ a conflict of torch versions. There are quite a few posts about this- the following possible solutions are mentioned:
- Uninstall and reinstall torch
- pip install --upgrade transformers
- https://github.com/nmilosev/pytorch-arm-builds/blob/master/README.md#9-import-errors

Can you let me know if any of these fix your issue and if so, which one? 

I didn't have this issue in the Google Colab when I tested it, but I will try to replicate the issue and update you if I find a fix too.

**Comment by lyie28** [comment]
FYI, I just added some CI for the documentation in PR #187 which I hope should help us get rid of spelling errors & bad links!

**Comment by gbreed** [comment]
Firstly, what I've done is run through the instructions at https://docs.lavague.ai/en/latest/ with the OpenAI API key that the business has supplied me for testing this.  This worked with a few provisos


  *
I started in a virtualenv
  *
The initial apt command failed (something to so with the mantic index being out of date, the error has scrolled off the top of my session now and when I tried it again it worked) so I ran the commands from setup.sh manually
  *
I added an OPENAI_API_KEY to my environment (with export)
  *
I added "LaVague/" to the files from the example command, so that they came from the repository I cloned before

I gave up on huggingface because something else broke when I uninstalled and reinstalled torch.  I saved some of the terminal output from that.  Note that it started with something apparently going wrong installing torch and I don't know how this will end up formatted.  I can give this another try sometime: this is the end of the day for me

zsh: killed     pip install torch
(LaVague) 137 browser-test-22-04 ~/LaVague lavague -i huggingface.yaml -c huggin
gface_inference.py launch
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be ava
ilable and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "/home/graham/.virtualenvs/LaVague/lib/python3.11/site-packages/llama_ind
ex/core/utils.py", line 466, in infer_torch_device
    has_cuda = torch.cuda.is_available()
               ^^^^^
UnboundLocalError: cannot access local variable 'torch' where it is not associat
ed with a value

During handling of the above exception, another exception occurred:



  File "/home/graham/LaVague/huggingface_inference.py", line 44, in __init__
    super().__init__(model_name, device)
  File "/home/graham/.virtualenvs/LaVague/lib/python3.11/site-packages/llama_ind
ex/embeddings/huggingface/base.py", line 72, in __init__
    self._device = device or infer_torch_device()
                             ^^^^^^^^^^^^^^^^^^^^
  File "/home/graham/.virtualenvs/LaVague/lib/python3.11/site-packages/llama_ind
ex/core/utils.py", line 470, in infer_torch_device
    has_cuda = torch.cuda.is_available()
               ^^^^^^^^^^
AttributeError: module 'torch' has no attribute 'cuda'


________________________________

**Comment by lyie28** [comment]
Sorry for note getting back to you before.

The codebase has changed a lot since you opened this.

We now leverage three actions to complete the whole agent life cycle:
- A multi-modal LLM that generates the next instruction to achieve a goal
- An embedding modal used when we retrieve the most relevant chunks of HTML code
- An Action Engine LLM that generates the code for actions based on the latest instruction

The embedding model and Action Engine LLM can still be replaced with HuggingFace models. The multi-modal model can be any multi-modal LLM supported by any multi-modal models supported by LlamaIndex but unfortunately there is not a HF integration yet.

Feel free to test it out the latest changes and open an issue if you run into any more issues:
https://docs.lavague.ai/en/latest/docs/get-started/quick-tour/
