### ISSUE TITLE
VS Code extension, prompting a second time doesn't work or is extremely slow

### ISSUE THREAD

**Issue by paulpalmieri** [lavague-ai/LaVague#177]
**Describe the bug**
After running the boilerplate cell, the first prompt cell and the first generated code cell, I create a new cell to enter another prompt. 
This second prompt usually takes 30+ seconds and outputs a partially working cell

**To Reproduce**
I am on OSX (this is why you see me replacing the boilerplate at the start of the video)
1. Create new project with extension
2. Run boilerplate
3. Run generated cell
4. Create a new cell and input ```%lavague_exec "myprompt"```
5. Wait for processing

**Expected behavior**
Should be faster and properly output code cells

**Screenshots**
[See video (free hosting, will expire in 48h) ](https://streamable.com/fpxvyd)
Or ping me so that I send you the file!

**Comment by lyie28** [comment]
I cannot consistently reproduce this issue. But I think the VSCode extension was not designed to be able to have:
- Instruction/ magic command
- generated code
- New instruction/magic command cell

When I tested, it will replace the previous generated code rather than create a new cell. Can you confirm that this is expected (in the sense it is the current known functioning of the extension) @JoFrost ?

If so, I would propose we add supporting new commands in new cells as a help-wanted issue?

**Comment by JoFrost** [comment]
Hm. It's indeed supposed to replace the old cell. If it can, it will target a new cell.
I'm surprised however that the code is not fully sent. My guess is that the process fail on the python side.

@paulpalmieri I would like to get the file if possible.
