### ISSUE TITLE
Add option to Selenium Driver that accepts a `selenium.webdriver.chrome.options` options argument

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#360]
Optionally, users should be able to provide an `options` argument that will be passed to our webdriver in the SeleniumDriver `init` method.

File to be updated: `LaVague/tree/main/lavague-integrations/drivers/lavague-drivers-selenium/lavague/drivers/selenium/base.py`

Method to be updated: `def default_init_code(self) -> Any:`
 
 Task details: If `options` provided, pass this to webdriver instead of instantiating our own Options().

**Comment by shawon-majid** [comment]
Hi, the issue looks simple, I'm new to open source, as I've understand the issue:
1. I need to import Options from selenium chrome webdriver
2. need to pass an optional parameter for options in the init method for object instantiation
3. also assign the options in the self (as class variable)
4. just need to check whether self.options exists or not if exists assign it to chrome option otherwise create the Options() object like before

I think I can do the task. Assign me if you think that I'm on the right track! Thank you

**Comment by lyie28** [comment]
@shawon-majid - yes that's it. The import should already be in the code but for the other steps, yes, that should be it :)

**Comment by JoFrost** [comment]
Merged
