### ISSUE TITLE
Add LiteLLM support so that we can use 100+ Different LLM's easily with this project 

### ISSUE THREAD

**Issue by HakaishinShwet** [lavague-ai/LaVague#48]
Litellm is open source project you can read about them if you want https://github.com/BerriAI/litellm
Many projects are integrating with it because with this we can use easily 100+ different LLMs as it helps in creating local proxy server which api structure is open ai compatible and with one apo structure it becomes easy to change model and api key and use easily without additional configurations and reading and implementing from individual llm docs so please think about it

**Comment by dhuynh95** [comment]
We can do an integration with them.

Could you have a look at how we do [integrations ](https://github.com/lavague-ai/LaVague/tree/main/examples/api)and integrate [Llama(index's integration of LiteLLM](https://docs.llamaindex.ai/en/stable/examples/llm/litellm.html#litellm)?

**Comment by isaac-chung** [comment]
Just started a draft to gauge if I'm in the right direction.

**Comment by emrgnt-cmplxty** [comment]
Alternatively, you could use this as an opportunity to migrate to a easier to maintain/simpler RAG system like R2R (which is powered by LiteLLM) -  https://github.com/SciPhi-AI/R2R.

I would be happy to help with the migration if there is any interest.

**Comment by tomlavez** [comment]
I'm trying to replicate the azure example using LiteLLM but i'm facing a 404, probably because my endpoint is being messed up at some point. It should make a request at "<my-link>" but it is instead making at "<my-link>/openai/deployments/gpt-4o/chat/completions?api-version=2023-07-01-preview" which don't exist in my litellm.

Can you guys help me with this problem? Or drop an example on how i should use lavague with litellm
