### ISSUE TITLE
Stand alone docker for offline execution

### ISSUE THREAD

**Issue by vitalyshalumov** [lavague-ai/LaVague#83]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lyie28** [comment]
Hi @vitalyshalumov - can you provide more details of what you want? There is a Dockerfile in the /docker folder - is that what you are after?

**Comment by vitalyshalumov** [comment]
I want a stand-alone docker image with all the relevant libraries installed, which I can run with docker run - similar to: https://github.com/h2oai/h2ogpt/blob/main/docs/README_DOCKER.md

**Comment by lyie28** [comment]
We have an image, you don't need to install anything - the only thing is that for now you do need to supply our lavague-files folder as a mounted volume so you need to git clone the repo or download that folder but I am going to update the image so that is not necessary in the future.

Instructions for using the docker image are here in the LaVague with docker section: https://docs.lavague.ai/en/latest/docs/get-started/setting-up-la-vague/

**Comment by vitalyshalumov** [comment]
Thank you!
