### ISSUE TITLE
Add new Re-submit button for Python code generated

### ISSUE THREAD

**Issue by trongtran** [lavague-ai/LaVague#93]
After the Python code is generated. I want to change directly code generated and re-run it to see how it work instead of rewrite query

**Comment by lyie28** [comment]
That could be interesting. This would involve modified the Gradio code in the command_center. I will set it as help-wanted because we all have quite a few tasks  on our plates internally for now but maybe someone will take this from the community! Or if you want to give it a go, that would be great!

**Comment by shubhamofbce** [comment]
We are also working on a VS code extension which will make this possible soon.

**Comment by shivamsharma00** [comment]
I would like to work on this issue.

**Comment by lyie28** [comment]
Sounds great @shivamsharma00. I'll set the issue to community assigned. Let me know if you need any more info about this one

**Comment by lyie28** [comment]
This is now handled by an automatic retry mechanism if steps fail
