### ISSUE TITLE
Is it possible to generate for other languages? (Java, Javascript, Typescript...)?

### ISSUE THREAD

**Issue by trongtran** [lavague-ai/LaVague#94]
I've tried to change code & rebuild for supporting Java, but it thrown error because Java doesn't support by Gradio component. Can you please give guideline to how to support other language (e,g: javascript) ?

**gradio/components/code.py**
```
    languages = [
        "python",
        "markdown",
        "json",
        "html",
        "css",
        "javascript",
        "typescript",
        "yaml",
        "dockerfile",
        "shell",
        "r",
        "sql",
        "sql-msSQL",
        "sql-mySQL",
        "sql-mariaDB",
        "sql-sqlite",
        "sql-cassandra",
        "sql-plSQL",
        "sql-hive",
        "sql-pgSQL",
        "sql-gql",
        "sql-gpSQL",
        "sql-sparkSQL",
        "sql-esper",
        None,
    ]

```

**Comment by lyie28** [comment]
Hi @trongtran, to generate the code in Java/JavaScript/Typescript leveraging Selenium, I  would recommend focusing on generating the code with the 'lavague-build' command. You can then execute the generated code directly locally. Note you should remove the 'headless' option from the generated code if you want to see the action in your GUI.

Have you created a custom prompt in prompts.py which you use instead of our default one (which basically requests code to be generated in python leveraging Selenium)?

If you get this working, would be great if you want to share it on our 'show-your-work' channel on our Discord server by the way!

With the Gradio generated with the lavague-launch, we execute the code generated with the Python exec() method, so this will only work with Python. You could play around with modifying the Python code in the Gradio section on command_center.py, maybe try and save the generated code as a file and execute it with os.system() or as a subprocess - but we've never tried/tested this.

**Comment by trongtran** [comment]
@lyie28 Thank you for your comment. I will review it and follow your suggestion to try it, and I'll update you with the results later.

**Comment by lyie28** [comment]
Oh and you'll also need to add and use a new cleaning function as we clean the generated code to get to the first bit of python code by default
You can just define a new cleaning function in your config file, see docs on how to do this here: https://docs.lavague.ai/en/latest/docs/get-started/customization/

**Comment by lyie28** [comment]
Will close this one for now since there has not been any new activity for a while. Feel free to join us on Discord to discuss further!
